// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daily_reports.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDailyReportByDate = `-- name: GetDailyReportByDate :one
SELECT report_date, meal_count, total_sugar_grams, average_sugar_grams, highest_risk_level, summary, ai_insights, ai_insight_source, ai_insight_status
FROM daily_reports
WHERE report_date = $1
`

func (q *Queries) GetDailyReportByDate(ctx context.Context, reportDate pgtype.Date) (DailyReport, error) {
	row := q.db.QueryRow(ctx, getDailyReportByDate, reportDate)
	var i DailyReport
	err := row.Scan(
		&i.ReportDate,
		&i.MealCount,
		&i.TotalSugarGrams,
		&i.AverageSugarGrams,
		&i.HighestRiskLevel,
		&i.Summary,
		&i.AiInsights,
		&i.AiInsightSource,
		&i.AiInsightStatus,
	)
	return i, err
}

const upsertDailyReport = `-- name: UpsertDailyReport :exec
INSERT INTO daily_reports (
    report_date,
    meal_count,
    total_sugar_grams,
    average_sugar_grams,
    highest_risk_level,
    summary,
    ai_insights,
    ai_insight_source,
    ai_insight_status
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
ON CONFLICT (report_date) DO UPDATE SET
    meal_count = EXCLUDED.meal_count,
    total_sugar_grams = EXCLUDED.total_sugar_grams,
    average_sugar_grams = EXCLUDED.average_sugar_grams,
    highest_risk_level = EXCLUDED.highest_risk_level,
    summary = EXCLUDED.summary,
    ai_insights = EXCLUDED.ai_insights,
    ai_insight_source = EXCLUDED.ai_insight_source,
    ai_insight_status = EXCLUDED.ai_insight_status
`

type UpsertDailyReportParams struct {
	ReportDate        pgtype.Date `json:"report_date"`
	MealCount         int32       `json:"meal_count"`
	TotalSugarGrams   float64     `json:"total_sugar_grams"`
	AverageSugarGrams float64     `json:"average_sugar_grams"`
	HighestRiskLevel  string      `json:"highest_risk_level"`
	Summary           string      `json:"summary"`
	AiInsights        []byte      `json:"ai_insights"`
	AiInsightSource   string      `json:"ai_insight_source"`
	AiInsightStatus   string      `json:"ai_insight_status"`
}

func (q *Queries) UpsertDailyReport(ctx context.Context, arg UpsertDailyReportParams) error {
	_, err := q.db.Exec(ctx, upsertDailyReport,
		arg.ReportDate,
		arg.MealCount,
		arg.TotalSugarGrams,
		arg.AverageSugarGrams,
		arg.HighestRiskLevel,
		arg.Summary,
		arg.AiInsights,
		arg.AiInsightSource,
		arg.AiInsightStatus,
	)
	return err
}
