// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insights.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getInsightDailySugar = `-- name: GetInsightDailySugar :many
SELECT
    (recorded_at AT TIME ZONE $1::text)::date AS date,
    COALESCE(SUM(estimated_sugar_grams), 0)::double precision AS total_sugar_grams,
    COALESCE(SUM(estimated_calories), 0)::bigint AS total_calories,
    COALESCE(SUM(estimated_carbs_grams), 0)::double precision AS total_carbs_grams,
    COALESCE(SUM(estimated_protein_grams), 0)::double precision AS total_protein_grams,
    COUNT(*)::bigint AS meal_count,
    CASE
        WHEN MAX(CASE risk_level WHEN 'high' THEN 3 WHEN 'medium' THEN 2 WHEN 'low' THEN 1 ELSE 0 END) = 3 THEN 'high'
        WHEN MAX(CASE risk_level WHEN 'high' THEN 3 WHEN 'medium' THEN 2 WHEN 'low' THEN 1 ELSE 0 END) = 2 THEN 'medium'
        WHEN MAX(CASE risk_level WHEN 'high' THEN 3 WHEN 'medium' THEN 2 WHEN 'low' THEN 1 ELSE 0 END) = 1 THEN 'low'
        ELSE 'none'
    END AS risk_level
FROM meals
WHERE deleted_at IS NULL
  AND analysis_status = 'completed'
  AND estimated_sugar_grams IS NOT NULL
  AND recorded_at >= $2
  AND recorded_at < $3
GROUP BY (recorded_at AT TIME ZONE $1::text)::date
ORDER BY date
`

type GetInsightDailySugarParams struct {
	TimezoneName  string             `json:"timezone_name"`
	FromInclusive pgtype.Timestamptz `json:"from_inclusive"`
	ToExclusive   pgtype.Timestamptz `json:"to_exclusive"`
}

type GetInsightDailySugarRow struct {
	Date              pgtype.Date `json:"date"`
	TotalSugarGrams   float64     `json:"total_sugar_grams"`
	TotalCalories     int64       `json:"total_calories"`
	TotalCarbsGrams   float64     `json:"total_carbs_grams"`
	TotalProteinGrams float64     `json:"total_protein_grams"`
	MealCount         int64       `json:"meal_count"`
	RiskLevel         string      `json:"risk_level"`
}

func (q *Queries) GetInsightDailySugar(ctx context.Context, arg GetInsightDailySugarParams) ([]GetInsightDailySugarRow, error) {
	rows, err := q.db.Query(ctx, getInsightDailySugar, arg.TimezoneName, arg.FromInclusive, arg.ToExclusive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInsightDailySugarRow
	for rows.Next() {
		var i GetInsightDailySugarRow
		if err := rows.Scan(
			&i.Date,
			&i.TotalSugarGrams,
			&i.TotalCalories,
			&i.TotalCarbsGrams,
			&i.TotalProteinGrams,
			&i.MealCount,
			&i.RiskLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInsightMealTypeBreakdown = `-- name: GetInsightMealTypeBreakdown :many
SELECT
    COALESCE(NULLIF(TRIM(meal_type), ''), 'unknown')::text AS meal_type,
    COALESCE(SUM(estimated_sugar_grams), 0)::double precision AS total_sugar_grams,
    COUNT(*)::bigint AS meal_count,
    COALESCE(AVG(estimated_sugar_grams), 0)::double precision AS average_sugar_grams
FROM meals
WHERE deleted_at IS NULL
  AND analysis_status = 'completed'
  AND estimated_sugar_grams IS NOT NULL
  AND recorded_at >= $1
  AND recorded_at < $2
GROUP BY COALESCE(NULLIF(TRIM(meal_type), ''), 'unknown')
ORDER BY total_sugar_grams DESC
`

type GetInsightMealTypeBreakdownParams struct {
	FromInclusive pgtype.Timestamptz `json:"from_inclusive"`
	ToExclusive   pgtype.Timestamptz `json:"to_exclusive"`
}

type GetInsightMealTypeBreakdownRow struct {
	MealType          string  `json:"meal_type"`
	TotalSugarGrams   float64 `json:"total_sugar_grams"`
	MealCount         int64   `json:"meal_count"`
	AverageSugarGrams float64 `json:"average_sugar_grams"`
}

func (q *Queries) GetInsightMealTypeBreakdown(ctx context.Context, arg GetInsightMealTypeBreakdownParams) ([]GetInsightMealTypeBreakdownRow, error) {
	rows, err := q.db.Query(ctx, getInsightMealTypeBreakdown, arg.FromInclusive, arg.ToExclusive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInsightMealTypeBreakdownRow
	for rows.Next() {
		var i GetInsightMealTypeBreakdownRow
		if err := rows.Scan(
			&i.MealType,
			&i.TotalSugarGrams,
			&i.MealCount,
			&i.AverageSugarGrams,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInsightPeriodStats = `-- name: GetInsightPeriodStats :one

SELECT
    COALESCE(SUM(estimated_sugar_grams), 0)::double precision AS total_sugar_grams,
    COUNT(*)::bigint AS meal_count,
    COUNT(*) FILTER (WHERE risk_level = 'high')::bigint AS high_risk_meals
FROM meals
WHERE deleted_at IS NULL
  AND analysis_status = 'completed'
  AND estimated_sugar_grams IS NOT NULL
  AND recorded_at >= $1
  AND recorded_at < $2
`

type GetInsightPeriodStatsParams struct {
	FromInclusive pgtype.Timestamptz `json:"from_inclusive"`
	ToExclusive   pgtype.Timestamptz `json:"to_exclusive"`
}

type GetInsightPeriodStatsRow struct {
	TotalSugarGrams float64 `json:"total_sugar_grams"`
	MealCount       int64   `json:"meal_count"`
	HighRiskMeals   int64   `json:"high_risk_meals"`
}

// Insight queries intentionally do not scope by user yet.
// TODO: add user_id filter when the meals table supports users.
func (q *Queries) GetInsightPeriodStats(ctx context.Context, arg GetInsightPeriodStatsParams) (GetInsightPeriodStatsRow, error) {
	row := q.db.QueryRow(ctx, getInsightPeriodStats, arg.FromInclusive, arg.ToExclusive)
	var i GetInsightPeriodStatsRow
	err := row.Scan(&i.TotalSugarGrams, &i.MealCount, &i.HighRiskMeals)
	return i, err
}

const getInsightRiskDistribution = `-- name: GetInsightRiskDistribution :many
SELECT
    COALESCE(NULLIF(TRIM(risk_level), ''), 'unknown')::text AS risk_level,
    COUNT(*)::bigint AS count
FROM meals
WHERE deleted_at IS NULL
  AND analysis_status = 'completed'
  AND estimated_sugar_grams IS NOT NULL
  AND recorded_at >= $1
  AND recorded_at < $2
GROUP BY COALESCE(NULLIF(TRIM(risk_level), ''), 'unknown')
ORDER BY count DESC, risk_level ASC
`

type GetInsightRiskDistributionParams struct {
	FromInclusive pgtype.Timestamptz `json:"from_inclusive"`
	ToExclusive   pgtype.Timestamptz `json:"to_exclusive"`
}

type GetInsightRiskDistributionRow struct {
	RiskLevel string `json:"risk_level"`
	Count     int64  `json:"count"`
}

func (q *Queries) GetInsightRiskDistribution(ctx context.Context, arg GetInsightRiskDistributionParams) ([]GetInsightRiskDistributionRow, error) {
	rows, err := q.db.Query(ctx, getInsightRiskDistribution, arg.FromInclusive, arg.ToExclusive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInsightRiskDistributionRow
	for rows.Next() {
		var i GetInsightRiskDistributionRow
		if err := rows.Scan(&i.RiskLevel, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInsightSugarVsCalories = `-- name: GetInsightSugarVsCalories :many
SELECT
    id AS meal_id,
    dish_name,
    estimated_sugar_grams AS sugar_grams,
    estimated_calories AS calories,
    risk_level,
    recorded_at
FROM meals
WHERE deleted_at IS NULL
  AND analysis_status = 'completed'
  AND estimated_sugar_grams IS NOT NULL
  AND estimated_calories IS NOT NULL
  AND recorded_at >= $1
  AND recorded_at < $2
ORDER BY recorded_at DESC, id DESC
LIMIT 100
`

type GetInsightSugarVsCaloriesParams struct {
	FromInclusive pgtype.Timestamptz `json:"from_inclusive"`
	ToExclusive   pgtype.Timestamptz `json:"to_exclusive"`
}

type GetInsightSugarVsCaloriesRow struct {
	MealID     int64              `json:"meal_id"`
	DishName   string             `json:"dish_name"`
	SugarGrams float64            `json:"sugar_grams"`
	Calories   int32              `json:"calories"`
	RiskLevel  string             `json:"risk_level"`
	RecordedAt pgtype.Timestamptz `json:"recorded_at"`
}

func (q *Queries) GetInsightSugarVsCalories(ctx context.Context, arg GetInsightSugarVsCaloriesParams) ([]GetInsightSugarVsCaloriesRow, error) {
	rows, err := q.db.Query(ctx, getInsightSugarVsCalories, arg.FromInclusive, arg.ToExclusive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInsightSugarVsCaloriesRow
	for rows.Next() {
		var i GetInsightSugarVsCaloriesRow
		if err := rows.Scan(
			&i.MealID,
			&i.DishName,
			&i.SugarGrams,
			&i.Calories,
			&i.RiskLevel,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInsightTopSugarDishes = `-- name: GetInsightTopSugarDishes :many
SELECT
    TRIM(dish_name)::text AS dish_name,
    COUNT(*)::bigint AS times_logged,
    COALESCE(SUM(estimated_sugar_grams), 0)::double precision AS total_sugar_grams,
    COALESCE(AVG(estimated_sugar_grams), 0)::double precision AS average_sugar_grams
FROM meals
WHERE deleted_at IS NULL
  AND analysis_status = 'completed'
  AND estimated_sugar_grams IS NOT NULL
  AND NULLIF(TRIM(dish_name), '') IS NOT NULL
  AND recorded_at >= $1
  AND recorded_at < $2
GROUP BY TRIM(dish_name)
ORDER BY total_sugar_grams DESC, times_logged DESC
LIMIT 5
`

type GetInsightTopSugarDishesParams struct {
	FromInclusive pgtype.Timestamptz `json:"from_inclusive"`
	ToExclusive   pgtype.Timestamptz `json:"to_exclusive"`
}

type GetInsightTopSugarDishesRow struct {
	DishName          string  `json:"dish_name"`
	TimesLogged       int64   `json:"times_logged"`
	TotalSugarGrams   float64 `json:"total_sugar_grams"`
	AverageSugarGrams float64 `json:"average_sugar_grams"`
}

func (q *Queries) GetInsightTopSugarDishes(ctx context.Context, arg GetInsightTopSugarDishesParams) ([]GetInsightTopSugarDishesRow, error) {
	rows, err := q.db.Query(ctx, getInsightTopSugarDishes, arg.FromInclusive, arg.ToExclusive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInsightTopSugarDishesRow
	for rows.Next() {
		var i GetInsightTopSugarDishesRow
		if err := rows.Scan(
			&i.DishName,
			&i.TimesLogged,
			&i.TotalSugarGrams,
			&i.AverageSugarGrams,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInsightTopSugarMeals = `-- name: GetInsightTopSugarMeals :many
SELECT
    id AS meal_id,
    dish_name,
    estimated_sugar_grams AS sugar_grams,
    estimated_calories AS calories,
    meal_type,
    risk_level,
    recorded_at
FROM meals
WHERE deleted_at IS NULL
  AND analysis_status = 'completed'
  AND estimated_sugar_grams IS NOT NULL
  AND recorded_at >= $1
  AND recorded_at < $2
ORDER BY estimated_sugar_grams DESC, recorded_at DESC, id DESC
LIMIT 5
`

type GetInsightTopSugarMealsParams struct {
	FromInclusive pgtype.Timestamptz `json:"from_inclusive"`
	ToExclusive   pgtype.Timestamptz `json:"to_exclusive"`
}

type GetInsightTopSugarMealsRow struct {
	MealID     int64              `json:"meal_id"`
	DishName   string             `json:"dish_name"`
	SugarGrams float64            `json:"sugar_grams"`
	Calories   int32              `json:"calories"`
	MealType   string             `json:"meal_type"`
	RiskLevel  string             `json:"risk_level"`
	RecordedAt pgtype.Timestamptz `json:"recorded_at"`
}

func (q *Queries) GetInsightTopSugarMeals(ctx context.Context, arg GetInsightTopSugarMealsParams) ([]GetInsightTopSugarMealsRow, error) {
	rows, err := q.db.Query(ctx, getInsightTopSugarMeals, arg.FromInclusive, arg.ToExclusive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInsightTopSugarMealsRow
	for rows.Next() {
		var i GetInsightTopSugarMealsRow
		if err := rows.Scan(
			&i.MealID,
			&i.DishName,
			&i.SugarGrams,
			&i.Calories,
			&i.MealType,
			&i.RiskLevel,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInsightWeeklySugar = `-- name: GetInsightWeeklySugar :many
SELECT
    date_trunc('week', recorded_at AT TIME ZONE $1::text)::date AS week_start,
    COALESCE(SUM(estimated_sugar_grams), 0)::double precision AS total_sugar_grams,
    COALESCE(SUM(estimated_sugar_grams) / NULLIF(COUNT(DISTINCT (recorded_at AT TIME ZONE $1::text)::date), 0), 0)::double precision AS average_per_day,
    COUNT(*)::bigint AS meal_count,
    COUNT(*) FILTER (WHERE risk_level = 'high')::bigint AS high_risk_meals
FROM meals
WHERE deleted_at IS NULL
  AND analysis_status = 'completed'
  AND estimated_sugar_grams IS NOT NULL
  AND recorded_at >= $2
  AND recorded_at < $3
GROUP BY date_trunc('week', recorded_at AT TIME ZONE $1::text)::date
ORDER BY week_start ASC
`

type GetInsightWeeklySugarParams struct {
	TimezoneName  string             `json:"timezone_name"`
	FromInclusive pgtype.Timestamptz `json:"from_inclusive"`
	ToExclusive   pgtype.Timestamptz `json:"to_exclusive"`
}

type GetInsightWeeklySugarRow struct {
	WeekStart       pgtype.Date `json:"week_start"`
	TotalSugarGrams float64     `json:"total_sugar_grams"`
	AveragePerDay   float64     `json:"average_per_day"`
	MealCount       int64       `json:"meal_count"`
	HighRiskMeals   int64       `json:"high_risk_meals"`
}

func (q *Queries) GetInsightWeeklySugar(ctx context.Context, arg GetInsightWeeklySugarParams) ([]GetInsightWeeklySugarRow, error) {
	rows, err := q.db.Query(ctx, getInsightWeeklySugar, arg.TimezoneName, arg.FromInclusive, arg.ToExclusive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInsightWeeklySugarRow
	for rows.Next() {
		var i GetInsightWeeklySugarRow
		if err := rows.Scan(
			&i.WeekStart,
			&i.TotalSugarGrams,
			&i.AveragePerDay,
			&i.MealCount,
			&i.HighRiskMeals,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
