// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meals.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMeal = `-- name: CreateMeal :one
INSERT INTO meals (
    dish_name,
    image_url,
    recorded_at,
    analysis_status,
    estimated_sugar_grams,
    estimated_calories,
    risk_level,
    analysis_notes
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, dish_name, image_url, recorded_at, analysis_status, estimated_sugar_grams, estimated_calories, risk_level, analysis_notes
`

type CreateMealParams struct {
	DishName            string             `json:"dish_name"`
	ImageUrl            *string            `json:"image_url"`
	RecordedAt          pgtype.Timestamptz `json:"recorded_at"`
	AnalysisStatus      string             `json:"analysis_status"`
	EstimatedSugarGrams float64            `json:"estimated_sugar_grams"`
	EstimatedCalories   int32              `json:"estimated_calories"`
	RiskLevel           string             `json:"risk_level"`
	AnalysisNotes       string             `json:"analysis_notes"`
}

func (q *Queries) CreateMeal(ctx context.Context, arg CreateMealParams) (Meal, error) {
	row := q.db.QueryRow(ctx, createMeal,
		arg.DishName,
		arg.ImageUrl,
		arg.RecordedAt,
		arg.AnalysisStatus,
		arg.EstimatedSugarGrams,
		arg.EstimatedCalories,
		arg.RiskLevel,
		arg.AnalysisNotes,
	)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.DishName,
		&i.ImageUrl,
		&i.RecordedAt,
		&i.AnalysisStatus,
		&i.EstimatedSugarGrams,
		&i.EstimatedCalories,
		&i.RiskLevel,
		&i.AnalysisNotes,
	)
	return i, err
}

const listMealsByDay = `-- name: ListMealsByDay :many
SELECT id, dish_name, image_url, recorded_at, analysis_status, estimated_sugar_grams, estimated_calories, risk_level, analysis_notes
FROM meals
WHERE recorded_at >= $1
  AND recorded_at < $2
ORDER BY recorded_at ASC
`

type ListMealsByDayParams struct {
	DayStart pgtype.Timestamptz `json:"day_start"`
	DayEnd   pgtype.Timestamptz `json:"day_end"`
}

func (q *Queries) ListMealsByDay(ctx context.Context, arg ListMealsByDayParams) ([]Meal, error) {
	rows, err := q.db.Query(ctx, listMealsByDay, arg.DayStart, arg.DayEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meal
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.ID,
			&i.DishName,
			&i.ImageUrl,
			&i.RecordedAt,
			&i.AnalysisStatus,
			&i.EstimatedSugarGrams,
			&i.EstimatedCalories,
			&i.RiskLevel,
			&i.AnalysisNotes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
