// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DailyReport struct {
	ReportDate        pgtype.Date `json:"report_date"`
	MealCount         int32       `json:"meal_count"`
	TotalSugarGrams   float64     `json:"total_sugar_grams"`
	AverageSugarGrams float64     `json:"average_sugar_grams"`
	HighestRiskLevel  string      `json:"highest_risk_level"`
	Summary           string      `json:"summary"`
	AiInsights        []byte      `json:"ai_insights"`
	AiInsightSource   string      `json:"ai_insight_source"`
	AiInsightStatus   string      `json:"ai_insight_status"`
}

type Meal struct {
	ID                    int64              `json:"id"`
	DishName              string             `json:"dish_name"`
	MealType              string             `json:"meal_type"`
	ImageUrl              *string            `json:"image_url"`
	RecordedAt            pgtype.Timestamptz `json:"recorded_at"`
	AnalysisStatus        string             `json:"analysis_status"`
	EstimatedSugarGrams   float64            `json:"estimated_sugar_grams"`
	EstimatedCarbsGrams   float64            `json:"estimated_carbs_grams"`
	EstimatedProteinGrams float64            `json:"estimated_protein_grams"`
	EstimatedCalories     int32              `json:"estimated_calories"`
	RiskLevel             string             `json:"risk_level"`
	AnalysisNotes         string             `json:"analysis_notes"`
	IsUserEdited          bool               `json:"is_user_edited"`
	AnalysisRetryCount    int32              `json:"analysis_retry_count"`
	LastAnalysisAttemptAt pgtype.Timestamptz `json:"last_analysis_attempt_at"`
	DeletedAt             pgtype.Timestamptz `json:"deleted_at"`
}

type WeeklyReport struct {
	WeekStartDate     pgtype.Date        `json:"week_start_date"`
	WeekEndDate       pgtype.Date        `json:"week_end_date"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	MealCount         int32              `json:"meal_count"`
	AnalyzedMealCount int32              `json:"analyzed_meal_count"`
	TotalSugarGrams   float64            `json:"total_sugar_grams"`
	AverageSugarGrams float64            `json:"average_sugar_grams"`
	HighestRiskLevel  string             `json:"highest_risk_level"`
	Summary           string             `json:"summary"`
	DailyBreakdown    []byte             `json:"daily_breakdown"`
	AiInsights        []byte             `json:"ai_insights"`
	AiInsightSource   string             `json:"ai_insight_source"`
	AiInsightStatus   string             `json:"ai_insight_status"`
}
