// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DailyReport struct {
	ReportDate        pgtype.Date `json:"report_date"`
	MealCount         int32       `json:"meal_count"`
	TotalSugarGrams   float64     `json:"total_sugar_grams"`
	AverageSugarGrams float64     `json:"average_sugar_grams"`
	HighestRiskLevel  string      `json:"highest_risk_level"`
	Summary           string      `json:"summary"`
}

type Meal struct {
	ID                  int64              `json:"id"`
	DishName            string             `json:"dish_name"`
	MealType            string             `json:"meal_type"`
	ImageUrl            *string            `json:"image_url"`
	RecordedAt          pgtype.Timestamptz `json:"recorded_at"`
	AnalysisStatus      string             `json:"analysis_status"`
	EstimatedSugarGrams float64            `json:"estimated_sugar_grams"`
	EstimatedCalories   int32              `json:"estimated_calories"`
	RiskLevel           string             `json:"risk_level"`
	AnalysisNotes       string             `json:"analysis_notes"`
}
