// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateMeal(ctx context.Context, arg CreateMealParams) (Meal, error)
	GetDailyReportByDate(ctx context.Context, reportDate pgtype.Date) (DailyReport, error)
	ListMealsByDay(ctx context.Context, arg ListMealsByDayParams) ([]Meal, error)
	UpsertDailyReport(ctx context.Context, arg UpsertDailyReportParams) error
}

var _ Querier = (*Queries)(nil)
