// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountMeals(ctx context.Context, arg CountMealsParams) (int64, error)
	CountRecentDistinctMeals(ctx context.Context, queryText string) (int64, error)
	CreateMeal(ctx context.Context, arg CreateMealParams) (Meal, error)
	GetDailyReportByDate(ctx context.Context, reportDate pgtype.Date) (DailyReport, error)
	GetInsightDailySugar(ctx context.Context, arg GetInsightDailySugarParams) ([]GetInsightDailySugarRow, error)
	GetInsightMealTypeBreakdown(ctx context.Context, arg GetInsightMealTypeBreakdownParams) ([]GetInsightMealTypeBreakdownRow, error)
	GetInsightPeriodStats(ctx context.Context, arg GetInsightPeriodStatsParams) (GetInsightPeriodStatsRow, error)
	GetInsightRiskDistribution(ctx context.Context, arg GetInsightRiskDistributionParams) ([]GetInsightRiskDistributionRow, error)
	GetInsightSugarVsCalories(ctx context.Context, arg GetInsightSugarVsCaloriesParams) ([]GetInsightSugarVsCaloriesRow, error)
	GetInsightTopSugarDishes(ctx context.Context, arg GetInsightTopSugarDishesParams) ([]GetInsightTopSugarDishesRow, error)
	GetInsightTopSugarMeals(ctx context.Context, arg GetInsightTopSugarMealsParams) ([]GetInsightTopSugarMealsRow, error)
	GetInsightWeeklySugar(ctx context.Context, arg GetInsightWeeklySugarParams) ([]GetInsightWeeklySugarRow, error)
	GetMealByID(ctx context.Context, id int64) (Meal, error)
	ListMeals(ctx context.Context, arg ListMealsParams) ([]Meal, error)
	ListMealsByDay(ctx context.Context, arg ListMealsByDayParams) ([]Meal, error)
	ListRecentDistinctMeals(ctx context.Context, arg ListRecentDistinctMealsParams) ([]ListRecentDistinctMealsRow, error)
	ListRetryableFailedMeals(ctx context.Context, arg ListRetryableFailedMealsParams) ([]Meal, error)
	RetryFailedMealAnalysisByID(ctx context.Context, id int64) (Meal, error)
	SoftDeleteMealByID(ctx context.Context, id int64) (int64, error)
	UpdateMealAnalysisByID(ctx context.Context, arg UpdateMealAnalysisByIDParams) (Meal, error)
	// Called by the async goroutine after AI analysis succeeds.
	// Sets all nutrition fields and marks analysis_status = 'completed'.
	UpdateMealAnalysisResultByID(ctx context.Context, arg UpdateMealAnalysisResultByIDParams) (Meal, error)
	// Called by the async goroutine when all retries are exhausted.
	UpdateMealAnalysisStatusByID(ctx context.Context, arg UpdateMealAnalysisStatusByIDParams) (int64, error)
	UpdateMealForReanalysisByID(ctx context.Context, arg UpdateMealForReanalysisByIDParams) (Meal, error)
	UpdateMealMetaByID(ctx context.Context, arg UpdateMealMetaByIDParams) (Meal, error)
	UpdateMealWithAnalysisByID(ctx context.Context, arg UpdateMealWithAnalysisByIDParams) (Meal, error)
	UpsertDailyReport(ctx context.Context, arg UpsertDailyReportParams) error
}

var _ Querier = (*Queries)(nil)
