// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: weekly_reports.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getWeeklyReportByWeekStart = `-- name: GetWeeklyReportByWeekStart :one
SELECT week_start_date, week_end_date, created_at, meal_count, analyzed_meal_count, total_sugar_grams, average_sugar_grams, highest_risk_level, summary, daily_breakdown, ai_insights, ai_insight_source, ai_insight_status
FROM weekly_reports
WHERE week_start_date = $1
`

func (q *Queries) GetWeeklyReportByWeekStart(ctx context.Context, weekStartDate pgtype.Date) (WeeklyReport, error) {
	row := q.db.QueryRow(ctx, getWeeklyReportByWeekStart, weekStartDate)
	var i WeeklyReport
	err := row.Scan(
		&i.WeekStartDate,
		&i.WeekEndDate,
		&i.CreatedAt,
		&i.MealCount,
		&i.AnalyzedMealCount,
		&i.TotalSugarGrams,
		&i.AverageSugarGrams,
		&i.HighestRiskLevel,
		&i.Summary,
		&i.DailyBreakdown,
		&i.AiInsights,
		&i.AiInsightSource,
		&i.AiInsightStatus,
	)
	return i, err
}

const upsertWeeklyReport = `-- name: UpsertWeeklyReport :exec
INSERT INTO weekly_reports (
    week_start_date,
    week_end_date,
    created_at,
    meal_count,
    analyzed_meal_count,
    total_sugar_grams,
    average_sugar_grams,
    highest_risk_level,
    summary,
    daily_breakdown,
    ai_insights,
    ai_insight_source,
    ai_insight_status
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13
)
ON CONFLICT (week_start_date) DO UPDATE SET
    week_end_date = EXCLUDED.week_end_date,
    meal_count = EXCLUDED.meal_count,
    analyzed_meal_count = EXCLUDED.analyzed_meal_count,
    total_sugar_grams = EXCLUDED.total_sugar_grams,
    average_sugar_grams = EXCLUDED.average_sugar_grams,
    highest_risk_level = EXCLUDED.highest_risk_level,
    summary = EXCLUDED.summary,
    daily_breakdown = EXCLUDED.daily_breakdown,
    ai_insights = EXCLUDED.ai_insights,
    ai_insight_source = EXCLUDED.ai_insight_source,
    ai_insight_status = EXCLUDED.ai_insight_status
`

type UpsertWeeklyReportParams struct {
	WeekStartDate     pgtype.Date        `json:"week_start_date"`
	WeekEndDate       pgtype.Date        `json:"week_end_date"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	MealCount         int32              `json:"meal_count"`
	AnalyzedMealCount int32              `json:"analyzed_meal_count"`
	TotalSugarGrams   float64            `json:"total_sugar_grams"`
	AverageSugarGrams float64            `json:"average_sugar_grams"`
	HighestRiskLevel  string             `json:"highest_risk_level"`
	Summary           string             `json:"summary"`
	DailyBreakdown    []byte             `json:"daily_breakdown"`
	AiInsights        []byte             `json:"ai_insights"`
	AiInsightSource   string             `json:"ai_insight_source"`
	AiInsightStatus   string             `json:"ai_insight_status"`
}

func (q *Queries) UpsertWeeklyReport(ctx context.Context, arg UpsertWeeklyReportParams) error {
	_, err := q.db.Exec(ctx, upsertWeeklyReport,
		arg.WeekStartDate,
		arg.WeekEndDate,
		arg.CreatedAt,
		arg.MealCount,
		arg.AnalyzedMealCount,
		arg.TotalSugarGrams,
		arg.AverageSugarGrams,
		arg.HighestRiskLevel,
		arg.Summary,
		arg.DailyBreakdown,
		arg.AiInsights,
		arg.AiInsightSource,
		arg.AiInsightStatus,
	)
	return err
}
